### PR TITLE
[Build] Ver1.0.0

### PR DESCRIPTION
**Pull request by 0seob**
Co-authored-by: Yoon Sang Jun [SangJunni@users.noreply.github.com](mailto:SangJunni@users.noreply.github.com)
Co-authored-by: Jaeyoung Shin [LimePencil@users.noreply.github.com](mailto:LimePencil@users.noreply.github.com)
Co-authored-by: Sungwoo Lee [lsvv1217@users.noreply.github.com](mailto:lsvv1217@users.noreply.github.com)
Co-authored-by: seong_jong [sjz1@users.noreply.github.com](mailto:sjz1@users.noreply.github.com)

### CODE REVIEW

**Review by lsvv1217 — APPROVED** [review]
Ver1.0 고생하셨습니다!

**Review by SangJunni — APPROVED** [review]
모두들 기본 버전 build까지 수고하셨습니다!

**Review by LimePencil — APPROVED** [review]
모두 다 수고하셨습니다!

**Review by sjz1 — COMMENTED** [review]
다들 version1 수고하셨습니다!

**Review by sjz1 — APPROVED** [review]
수고하셨습니다

**Pull request merged**
